neth adaptation to create mysql user/db

diff --git a/root/etc/e-smith/events/actions/nethserver-phpmyadmin-conf b/root/etc/e-smith/events/actions/nethserver-phpmyadmin-conf
--- a/root/etc/e-smith/events/actions/nethserver-phpmyadmin-conf
+++ b/root/etc/e-smith/events/actions/nethserver-phpmyadmin-conf
@@ -25,8 +25,95 @@ package esmith;
 use strict;
 use Errno;
 use esmith::util;
+use esmith::ConfigDB;
+#use NethServer::Password;
+
+exit(0) unless system('/usr/bin/mysql phpmyadmin  -e "describe pma_userconfig" &> /dev/null') != 0;
+
+### Creation of the mysql base for phpmyadmin
+### Creation also of a superadmin 'sqladmin'
+  my $DB = esmith::ConfigDB->open();
+  my $rec = $DB->get('phpmyadmin') || $DB->new_record('phpmyadmin', {type => 'configuration'});
+
+  my $db = $phpmyadmin{'DbName'} || 'phpmyadmin';
+  my $user = $phpmyadmin{'DbUser'} || 'phpmyadmin';
+
+# creation of two different password
+  my $pass = esmith::util::genRandomPassword('phpmyadmin') || die('Could not generate phpmyadmin password!');
+   $rec->set_prop('DbPassword', $pass); 
+  my $admpass = esmith::util::genRandomPassword('sqladmin') || die('Could not generate sqladmin  password!');
+   $rec->set_prop('sqladminPassword', $admpass);  
+
+# find where the sql file is stored
+  my $dbstruct = `rpm -qd smeserver-phpmyadmin | grep phpmyadmin.sql`;
+
+  my $commands = join("\n",
+                 "GRANT ALL PRIVILEGES ON `$db`.* TO '$user'\@'localhost' IDENTIFIED BY '$pass';",
+                 "GRANT ALL PRIVILEGES ON *.* TO sqladmin\@'localhost' IDENTIFIED BY '$admpass';",
+                 "FLUSH PRIVILEGES;",
+                 "CREATE DATABASE IF NOT EXISTS $db DEFAULT CHARACTER SET = 'utf8';",
+                 "REPLACE INTO user (host,user,password) VALUES ('localhost','$user', PASSWORD ('$pass'));",
+                 "REPLACE INTO db (host,db,user,select_priv, insert_priv, update_priv, delete_priv,create_priv, 
+                     alter_priv, index_priv, drop_priv, create_tmp_table_priv,grant_priv, 
+                     lock_tables_priv, references_priv) 
+                  VALUES ( 'localhost','$db','$user','Y', 'Y', 'Y', 'Y','Y', 'Y', 'Y', 'Y', 'Y','N', 'Y', 'Y');"
+) . "\n";
+
+   print $commands;
+   open(FH, '|-', '/usr/bin/mysql -B -f') || die("[ERROR] Could not connect to mysql");
+   print FH $commands;
+   close(FH);
 
 
+
+
+
+
+$OUT .= <<"END";
+#! /bin/sh
+
+if [ ! -d /var/lib/mysql/$db ]; then
+        /usr/bin/mysql -e 'create database $db'
+        /usr/bin/mysql $db < $dbstruct
+fi
+
+/usr/bin/mysql <<EOF
+USE mysql;
+
+REPLACE INTO user (  
+                     host,
+                     user,
+                     password)
+            VALUES ( 
+                     'localhost',
+                     '$user',
+                     PASSWORD ('$pass'));
+
+
+REPLACE INTO db (  
+                   host,
+                   db,
+                   user,
+                   select_priv, insert_priv, update_priv, delete_priv,
+                   create_priv, alter_priv, index_priv, drop_priv, create_tmp_table_priv,
+                   grant_priv, lock_tables_priv, references_priv)
+          VALUES ( 
+                   'localhost',
+                   '$db',
+                   '$user',
+                   'Y', 'Y', 'Y', 'Y',
+                   'Y', 'Y', 'Y', 'Y', 'Y',
+                   'N', 'Y', 'Y');
+
+GRANT ALL ON *.* TO 'sqladmin'\@'localhost' IDENTIFIED BY '$admpass'
+    WITH GRANT OPTION;
+
+FLUSH PRIVILEGES;
+EOF
+END
+
+
+### Creation of the user Admin with all permissions
 
   my $password = esmith::util::genRandomPassword('/etc/my.pwd')
         || die('Could not retrieve mysql password!');
@@ -46,4 +133,3 @@ if ($admin_condition =~ '0')
     }
 
 exit (0);
-
